import type { RecipeHit, RequirementDsl, SkillDagNode, SkillManifest } from "../../shared/domain";

export const atomicSkills: SkillManifest[] = [
  {
    id: "clarify-requirement",
    name: "Clarify Requirement",
    level: "atomic",
    capability: "识别歧义、冲突、角色、边界和验收缺口",
    inputContract: ["raw requirement"],
    outputContract: ["clarification questions", "assumptions"],
    preconditions: ["PM 输入非空"],
    postconditions: ["需求可以被标记为 ready、needs-clarification 或 contradictory"],
    ownedStacks: ["shared"],
    clarificationQuestions: ["缺少角色、数据来源、展示规则或验收标准时必须提问"],
    contextRequirements: ["历史交付记忆", "产品输入"],
    generationPromptTemplate: "Find ambiguity, contradiction, and missing acceptance criteria.",
    verificationCommands: ["npm run check"],
    failureModes: ["跳过歧义导致生成错误代码", "未识别矛盾需求"],
  },
  {
    id: "map-codebase-context",
    name: "Map Codebase Context",
    level: "atomic",
    capability: "根据 DSL 和仓库索引定位相关文件",
    inputContract: ["RequirementDsl", "RepositorySnapshot"],
    outputContract: ["ModuleTarget[]"],
    preconditions: ["目标仓可读"],
    postconditions: ["输出候选文件、存在性和定位理由"],
    ownedStacks: ["backend", "frontend", "test"],
    clarificationQuestions: [],
    contextRequirements: ["file tree", "package scripts", "routes", "models", "components"],
    generationPromptTemplate: "Map requirement intents to existing files and ownership boundaries.",
    verificationCommands: ["git status --short"],
    failureModes: ["漏掉跨栈传播目标", "误把仓库事实当成架构决策"],
  },
  {
    id: "add-data-field",
    name: "Add Data Field",
    level: "atomic",
    capability: "为持久化模型增加字段、默认值和迁移策略",
    inputContract: ["entity", "field"],
    outputContract: ["model change", "migration change"],
    preconditions: ["字段名、兼容策略明确"],
    postconditions: ["旧数据兼容，新字段可持久化"],
    ownedStacks: ["backend"],
    clarificationQuestions: ["旧数据默认行为是什么？"],
    contextRequirements: ["models", "migrations"],
    generationPromptTemplate: "Update persistence model and migration for the requested field.",
    verificationCommands: ["npm test -- --runInBand"],
    failureModes: ["只改模型不改迁移", "破坏旧数据兼容"],
  },
  {
    id: "update-api-contract",
    name: "Update API Contract",
    level: "atomic",
    capability: "更新请求参数、响应序列化和错误处理",
    inputContract: ["field contract", "controller files"],
    outputContract: ["API accepts and returns field"],
    preconditions: ["持久化字段已定义"],
    postconditions: ["读写 API 与模型一致"],
    ownedStacks: ["backend"],
    clarificationQuestions: ["字段是否需要格式校验？"],
    contextRequirements: ["controllers", "routes", "serializers"],
    generationPromptTemplate: "Propagate field through create, update, and read API paths.",
    verificationCommands: ["npm test"],
    failureModes: ["只写入不返回", "只返回不允许更新"],
  },
  {
    id: "update-frontend-form",
    name: "Update Frontend Form",
    level: "atomic",
    capability: "更新表单状态、校验、提交载荷和编辑回填",
    inputContract: ["API field contract", "form component"],
    outputContract: ["create/edit form supports field"],
    preconditions: ["API contract 明确"],
    postconditions: ["新建和编辑路径都包含字段"],
    ownedStacks: ["frontend"],
    clarificationQuestions: ["输入是否需要 URL 格式校验？"],
    contextRequirements: ["forms", "frontend services"],
    generationPromptTemplate: "Update form state, validation, payload, and edit hydration.",
    verificationCommands: ["npm run test -- --run"],
    failureModes: ["只改新建不改编辑", "提交载荷遗漏字段"],
  },
  {
    id: "update-frontend-rendering",
    name: "Update Frontend Rendering",
    level: "atomic",
    capability: "更新列表、详情、空态和兼容展示",
    inputContract: ["field display rule"],
    outputContract: ["list/detail rendering supports field"],
    preconditions: ["兼容展示规则明确"],
    postconditions: ["空值不破坏 UI"],
    ownedStacks: ["frontend"],
    clarificationQuestions: ["字段为空时隐藏还是占位？"],
    contextRequirements: ["list components", "detail components"],
    generationPromptTemplate: "Render field in all declared views with empty-state compatibility.",
    verificationCommands: ["npm run test -- --run"],
    failureModes: ["列表和详情展示不一致", "空值导致破图或布局错乱"],
  },
  {
    id: "generate-contract-tests",
    name: "Generate Contract Tests",
    level: "atomic",
    capability: "生成或更新跨栈契约测试",
    inputContract: ["ConsistencyContract"],
    outputContract: ["tests covering propagation targets"],
    preconditions: ["一致性合约已生成"],
    postconditions: ["关键传播路径有测试或验证证据"],
    ownedStacks: ["test"],
    clarificationQuestions: [],
    contextRequirements: ["existing tests", "test runner"],
    generationPromptTemplate: "Add tests for field propagation across backend and frontend.",
    verificationCommands: ["npm test"],
    failureModes: ["测试只覆盖单层", "忽略兼容旧数据"],
  },
  {
    id: "run-verification",
    name: "Run Verification",
    level: "atomic",
    capability: "执行目标仓验证命令并结构化结果",
    inputContract: ["verification commands"],
    outputContract: ["VerificationResult[]"],
    preconditions: ["工作区安全"],
    postconditions: ["验证结果可追踪"],
    ownedStacks: ["git", "test"],
    clarificationQuestions: [],
    contextRequirements: ["package scripts"],
    generationPromptTemplate: "Run lint, tests, build, and smoke checks when available.",
    verificationCommands: ["npm run lint", "npm test", "npm run build"],
    failureModes: ["忽略失败命令", "未记录输出证据"],
  },
  {
    id: "review-change",
    name: "Review Change",
    level: "atomic",
    capability: "检查跨栈一致性、风险、回归和缺失测试",
    inputContract: ["diff", "ConsistencyContract", "VerificationResult[]"],
    outputContract: ["review findings"],
    preconditions: ["变更和验证结果存在"],
    postconditions: ["高风险问题阻断提交"],
    ownedStacks: ["shared", "backend", "frontend", "test"],
    clarificationQuestions: [],
    contextRequirements: ["diff", "contracts", "events"],
    generationPromptTemplate: "Review behavior, consistency, regression risk, and test coverage.",
    verificationCommands: ["npm run check"],
    failureModes: ["把摘要当审查", "未阻断一致性失败"],
  },
];

export function planSkills(dsl: RequirementDsl): { dag: SkillDagNode[]; recipes: RecipeHit[] } {
  const articleField = dsl.intents.some(
    (intent) => intent.kind === "add-field" && intent.entity?.toLowerCase() === "article",
  );
  const base = [
    "clarify-requirement",
    "map-codebase-context",
    "add-data-field",
    "update-api-contract",
    "update-frontend-form",
    "update-frontend-rendering",
    "generate-contract-tests",
    "run-verification",
    "review-change",
  ];
  const skillIds = articleField ? base : ["clarify-requirement", "map-codebase-context", "run-verification", "review-change"];
  const dag = skillIds.map((skillId, index) => ({
    id: `node-${index + 1}`,
    skillId,
    dependsOn: index === 0 ? [] : [`node-${index}`],
    intentIds: dsl.intents.map((intent) => intent.id),
  }));
  const recipes: RecipeHit[] = articleField
    ? [
        {
          id: "recipe.article-field-extension",
          confidence: 0.92,
          reason: "需求包含 Article 新字段、持久化、API、表单、展示和契约测试传播链路。",
          skillIds: base.slice(2, 7),
        },
      ]
    : [];
  return { dag, recipes };
}
